from building import GetCurrentDir, DefineGroup
from os.path import join

cwd = GetCurrentDir()
src = Glob('src/*.c')
src += Glob('src/**/*.c')
# src += Glob('test/*.c')
# src += Glob('test/**/*.c')
CPPPATH = [join(cwd, 'inc')]

gcc_warn_flag = [
    'extra',
    'undef',
    'missing-declarations',
    'redundant-decls',
    'unreachable-code',
    'inline',
    'disabled-optimization',
    'error=implicit-function-declaration',
    'no-unused-parameter',
]

group = DefineGroup('Applications',
                    src,
                    depend=[''],
                    CPPPATH=CPPPATH,
                    LOCAL_CCFLAGS=' -W' + ' -W'.join(gcc_warn_flag) + ' ')

Return('group')
