from building import GetCurrentDir, DefineGroup
from os.path import join

cwd = GetCurrentDir()
src = Glob('src/*.c')
src += Glob('src/**/*.c')
CPPPATH = [join(cwd, 'inc')]

gcc_warn_flag = [
    'extra',
    'undef',
    'missing-declarations',
    'redundant-decls',
    'unreachable-code',
    'inline',
    'disabled-optimization',
    'error=implicit-function-declaration',
    'no-unused-parameter',
]

objs = []
objs += DefineGroup('Applications',
                    src,
                    depend=[''],
                    CPPPATH=CPPPATH,
                    LOCAL_CCFLAGS=' -DUSER_SCOPE -W' + ' -W'.join(gcc_warn_flag) + ' ')

src = Glob('shell/*.c')
src += Glob('shell/**/*.c')

objs += DefineGroup('ShellCmds',
                    src,
                    depend=['RT_USING_FINSH'],
                    CPPPATH=CPPPATH,
                    LOCAL_CCFLAGS=' -W' + ' -W'.join(gcc_warn_flag) + ' ')

Return('objs')
