from building import *
import rtconfig

cwd = GetCurrentDir()

src = ['ef_port.c']

if GetDepend(['PKG_USING_FAL']):
    src += ['ef_port_fal.c']
else:
    src += ['ef_port_raw.c']

CPPPATH = [cwd]

group = DefineGroup('EasyFlash',
                    src,
                    depend=['PKG_USING_EASYFLASH'],
                    CPPPATH=CPPPATH)

Return('group')
