import os
from building import *

objs = []
cwd = GetCurrentDir()

if GetDepend(['PKG_USING_FAL']):
    objs = objs + SConscript('fal/SConscript')
if GetDepend(['PKG_USING_EASYFLASH']):
    objs = objs + SConscript('easyflash/SConscript')

Return('objs')
